# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"3\n\x03Log\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"W\n\x0fRequestVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12\x12\n\nlast_index\x18\x03 \x01(\x05\x12\x11\n\tlast_term\x18\x04 \x01(\x05\"\x87\x01\n\x11\x41ppendEntriesArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12\x12\n\nprev_index\x18\x03 \x01(\x05\x12\x11\n\tprev_term\x18\x04 \x01(\x05\x12\x15\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x04.Log\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\".\n\x0eResultWithTerm\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\x08\n\x06NoArgs\"4\n\nLeaderResp\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x13\n\x0bleader_addr\x18\x02 \x01(\t\" \n\x0c\x44urationArgs\x12\x10\n\x08\x64uration\x18\x01 \x01(\x05\"*\n\x0cKeyValueArgs\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x16\n\x07KeyArgs\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x08\"0\n\x0fResultWithValue\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t2\x80\x02\n\x08RaftNode\x12\x30\n\x0bRequestVote\x12\x10.RequestVoteArgs\x1a\x0f.ResultWithTerm\x12\x34\n\rAppendEntries\x12\x12.AppendEntriesArgs\x1a\x0f.ResultWithTerm\x12!\n\tGetLeader\x12\x07.NoArgs\x1a\x0b.LeaderResp\x12!\n\x07Suspend\x12\r.DurationArgs\x1a\x07.NoArgs\x12 \n\x06SetVal\x12\r.KeyValueArgs\x1a\x07.Result\x12$\n\x06GetVal\x12\x08.KeyArgs\x1a\x10.ResultWithValueb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOG._serialized_start=14
  _LOG._serialized_end=65
  _REQUESTVOTEARGS._serialized_start=67
  _REQUESTVOTEARGS._serialized_end=154
  _APPENDENTRIESARGS._serialized_start=157
  _APPENDENTRIESARGS._serialized_end=292
  _RESULTWITHTERM._serialized_start=294
  _RESULTWITHTERM._serialized_end=340
  _NOARGS._serialized_start=342
  _NOARGS._serialized_end=350
  _LEADERRESP._serialized_start=352
  _LEADERRESP._serialized_end=404
  _DURATIONARGS._serialized_start=406
  _DURATIONARGS._serialized_end=438
  _KEYVALUEARGS._serialized_start=440
  _KEYVALUEARGS._serialized_end=482
  _KEYARGS._serialized_start=484
  _KEYARGS._serialized_end=506
  _RESULT._serialized_start=508
  _RESULT._serialized_end=532
  _RESULTWITHVALUE._serialized_start=534
  _RESULTWITHVALUE._serialized_end=582
  _RAFTNODE._serialized_start=585
  _RAFTNODE._serialized_end=841
# @@protoc_insertion_point(module_scope)
