# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class calculateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reverse = channel.unary_unary(
                '/calculate/reverse',
                request_serializer=service__pb2.Message.SerializeToString,
                response_deserializer=service__pb2.Message.FromString,
                )
        self.split = channel.unary_unary(
                '/calculate/split',
                request_serializer=service__pb2.splitRequest.SerializeToString,
                response_deserializer=service__pb2.splitResponse.FromString,
                )
        self.isprime = channel.stream_stream(
                '/calculate/isprime',
                request_serializer=service__pb2.isPrimeRequest.SerializeToString,
                response_deserializer=service__pb2.Message.FromString,
                )


class calculateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def split(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def isprime(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_calculateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reverse': grpc.unary_unary_rpc_method_handler(
                    servicer.reverse,
                    request_deserializer=service__pb2.Message.FromString,
                    response_serializer=service__pb2.Message.SerializeToString,
            ),
            'split': grpc.unary_unary_rpc_method_handler(
                    servicer.split,
                    request_deserializer=service__pb2.splitRequest.FromString,
                    response_serializer=service__pb2.splitResponse.SerializeToString,
            ),
            'isprime': grpc.stream_stream_rpc_method_handler(
                    servicer.isprime,
                    request_deserializer=service__pb2.isPrimeRequest.FromString,
                    response_serializer=service__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class calculate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculate/reverse',
            service__pb2.Message.SerializeToString,
            service__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def split(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculate/split',
            service__pb2.splitRequest.SerializeToString,
            service__pb2.splitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def isprime(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/calculate/isprime',
            service__pb2.isPrimeRequest.SerializeToString,
            service__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
