# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\"\x07\n\x05\x45mpty\"6\n\x13ResponseFingerTable\x12\x0e\n\x06nodeId\x18\x01 \x03(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x03(\t\"(\n\x0bRequestSave\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"-\n\x0eResponseAction\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\rRequestRemove\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1a\n\x0bRequestFind\x12\x0b\n\x03key\x18\x01 \x01(\t\"/\n\x0fRequestRegister\x12\x0e\n\x06ipaddr\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x03\"1\n\x10ResponseRegister\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x11RequestDeregister\x12\n\n\x02id\x18\x01 \x01(\x03\"3\n\x12ResponseDeregister\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x1aRequestPopulateFingerTable\x12\n\n\x02id\x18\x01 \x01(\x03\"#\n\x07\x41\x64\x64ress\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\"C\n\x1bResponsePopulateFingerTable\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x18\n\x06result\x18\x02 \x03(\x0b\x32\x08.Address\",\n\x10ResponseGetChord\x12\x18\n\x06result\x18\x01 \x03(\x0b\x32\x08.Address2\xb4\x01\n\x04Node\x12/\n\x0fGetFinger_table\x12\x06.Empty\x1a\x14.ResponseFingerTable\x12)\n\x08SaveData\x12\x0c.RequestSave\x1a\x0f.ResponseAction\x12)\n\x06Remove\x12\x0e.RequestRemove\x1a\x0f.ResponseAction\x12%\n\x04\x46ind\x12\x0c.RequestFind\x1a\x0f.ResponseAction2\xef\x01\n\x08Register\x12/\n\x08Register\x12\x10.RequestRegister\x1a\x11.ResponseRegister\x12\x35\n\nDeregister\x12\x12.RequestDeregister\x1a\x13.ResponseDeregister\x12P\n\x13PopulateFingerTable\x12\x1b.RequestPopulateFingerTable\x1a\x1c.ResponsePopulateFingerTable\x12)\n\x0cGetChordInfo\x12\x06.Empty\x1a\x11.ResponseGetChordb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_RESPONSEFINGERTABLE = DESCRIPTOR.message_types_by_name['ResponseFingerTable']
_REQUESTSAVE = DESCRIPTOR.message_types_by_name['RequestSave']
_RESPONSEACTION = DESCRIPTOR.message_types_by_name['ResponseAction']
_REQUESTREMOVE = DESCRIPTOR.message_types_by_name['RequestRemove']
_REQUESTFIND = DESCRIPTOR.message_types_by_name['RequestFind']
_REQUESTREGISTER = DESCRIPTOR.message_types_by_name['RequestRegister']
_RESPONSEREGISTER = DESCRIPTOR.message_types_by_name['ResponseRegister']
_REQUESTDEREGISTER = DESCRIPTOR.message_types_by_name['RequestDeregister']
_RESPONSEDEREGISTER = DESCRIPTOR.message_types_by_name['ResponseDeregister']
_REQUESTPOPULATEFINGERTABLE = DESCRIPTOR.message_types_by_name['RequestPopulateFingerTable']
_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_RESPONSEPOPULATEFINGERTABLE = DESCRIPTOR.message_types_by_name['ResponsePopulateFingerTable']
_RESPONSEGETCHORD = DESCRIPTOR.message_types_by_name['ResponseGetChord']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

ResponseFingerTable = _reflection.GeneratedProtocolMessageType('ResponseFingerTable', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEFINGERTABLE,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:ResponseFingerTable)
  })
_sym_db.RegisterMessage(ResponseFingerTable)

RequestSave = _reflection.GeneratedProtocolMessageType('RequestSave', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSAVE,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:RequestSave)
  })
_sym_db.RegisterMessage(RequestSave)

ResponseAction = _reflection.GeneratedProtocolMessageType('ResponseAction', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEACTION,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:ResponseAction)
  })
_sym_db.RegisterMessage(ResponseAction)

RequestRemove = _reflection.GeneratedProtocolMessageType('RequestRemove', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTREMOVE,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:RequestRemove)
  })
_sym_db.RegisterMessage(RequestRemove)

RequestFind = _reflection.GeneratedProtocolMessageType('RequestFind', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTFIND,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:RequestFind)
  })
_sym_db.RegisterMessage(RequestFind)

RequestRegister = _reflection.GeneratedProtocolMessageType('RequestRegister', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTREGISTER,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:RequestRegister)
  })
_sym_db.RegisterMessage(RequestRegister)

ResponseRegister = _reflection.GeneratedProtocolMessageType('ResponseRegister', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEREGISTER,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:ResponseRegister)
  })
_sym_db.RegisterMessage(ResponseRegister)

RequestDeregister = _reflection.GeneratedProtocolMessageType('RequestDeregister', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDEREGISTER,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:RequestDeregister)
  })
_sym_db.RegisterMessage(RequestDeregister)

ResponseDeregister = _reflection.GeneratedProtocolMessageType('ResponseDeregister', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDEREGISTER,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:ResponseDeregister)
  })
_sym_db.RegisterMessage(ResponseDeregister)

RequestPopulateFingerTable = _reflection.GeneratedProtocolMessageType('RequestPopulateFingerTable', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTPOPULATEFINGERTABLE,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:RequestPopulateFingerTable)
  })
_sym_db.RegisterMessage(RequestPopulateFingerTable)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:Address)
  })
_sym_db.RegisterMessage(Address)

ResponsePopulateFingerTable = _reflection.GeneratedProtocolMessageType('ResponsePopulateFingerTable', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEPOPULATEFINGERTABLE,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:ResponsePopulateFingerTable)
  })
_sym_db.RegisterMessage(ResponsePopulateFingerTable)

ResponseGetChord = _reflection.GeneratedProtocolMessageType('ResponseGetChord', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEGETCHORD,
  '__module__' : 'chord_pb2'
  # @@protoc_insertion_point(class_scope:ResponseGetChord)
  })
_sym_db.RegisterMessage(ResponseGetChord)

_NODE = DESCRIPTOR.services_by_name['Node']
_REGISTER = DESCRIPTOR.services_by_name['Register']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=15
  _EMPTY._serialized_end=22
  _RESPONSEFINGERTABLE._serialized_start=24
  _RESPONSEFINGERTABLE._serialized_end=78
  _REQUESTSAVE._serialized_start=80
  _REQUESTSAVE._serialized_end=120
  _RESPONSEACTION._serialized_start=122
  _RESPONSEACTION._serialized_end=167
  _REQUESTREMOVE._serialized_start=169
  _REQUESTREMOVE._serialized_end=197
  _REQUESTFIND._serialized_start=199
  _REQUESTFIND._serialized_end=225
  _REQUESTREGISTER._serialized_start=227
  _REQUESTREGISTER._serialized_end=274
  _RESPONSEREGISTER._serialized_start=276
  _RESPONSEREGISTER._serialized_end=325
  _REQUESTDEREGISTER._serialized_start=327
  _REQUESTDEREGISTER._serialized_end=358
  _RESPONSEDEREGISTER._serialized_start=360
  _RESPONSEDEREGISTER._serialized_end=411
  _REQUESTPOPULATEFINGERTABLE._serialized_start=413
  _REQUESTPOPULATEFINGERTABLE._serialized_end=453
  _ADDRESS._serialized_start=455
  _ADDRESS._serialized_end=490
  _RESPONSEPOPULATEFINGERTABLE._serialized_start=492
  _RESPONSEPOPULATEFINGERTABLE._serialized_end=559
  _RESPONSEGETCHORD._serialized_start=561
  _RESPONSEGETCHORD._serialized_end=605
  _NODE._serialized_start=608
  _NODE._serialized_end=788
  _REGISTER._serialized_start=791
  _REGISTER._serialized_end=1030
# @@protoc_insertion_point(module_scope)
